# Generated by Django 4.0.3 on 2022-03-18 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('87d5d929-bdbf-41dd-81ec-b9425fb72c06'), editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Disucssions',
            },
        ),
    ]
