# Generated by Django 4.0.3 on 2022-03-18 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('1f7b5a39-6630-4551-b998-43c213e75cc6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
