# Generated by Django 4.0.3 on 2022-03-18 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_discussion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('cf19459c-d01f-42ae-b04c-76b45e997066'), editable=False, primary_key=True, serialize=False),
        ),
    ]
