# Generated by Django 4.0.3 on 2022-03-20 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discussion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0ea92f41-c7f8-43aa-bf78-a5376098ad74'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('0ea92f41-c7f8-43aa-bf78-a5376098ad74'), editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(editable=False)),
                ('body', models.TextField()),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discussion')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_reply', to='core.reply')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
