# Generated by Django 4.0.3 on 2022-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_discussion_id_alter_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
