# Generated by Django 4.0.3 on 2022-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reply_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
